# Generated by Django 5.2.8 on 2025-11-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='demo_field',
            field=models.TextField(default='demo'),
        ),
    ]
